### ISSUE TITLE
STORY- Backend Adding Teams

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#24]
As a program manager, When I click the option for adding teams, the information pertaining to the team (team name) will be sent to the backend.

**Comment by haemanthisree** [comment]
Acceptance Test:

**Comment by Gitanjali2016** [comment]
Acceptance Test:
1) Go to the create page
2) Click on the team button
3) Add a team named A and a team named B
4) Click on the event button
5) Add Monday and Wednesday
6) Click on Submit Data
7) Press keys 'options' + 'ctrl' + i
8) Select console
9) The corresponding team with practice day will be printed on the console
This means that the team data has been sent to the backend to be processed since the output has all the team names we provided.
